# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  extra_joints:
      # - name:     'extra1'
      # position: 10.0
      # velocity: 20.0
      # effort:   30.0
    - name:     'fl_caster_rotation_joint'
    - name:     'fr_caster_rotation_joint'
    - name:     'bl_caster_rotation_joint'
    - name:     'br_caster_rotation_joint'
    - name:     'fl_caster_wheel_joint'
    - name:     'fr_caster_wheel_joint'
    - name:     'bl_caster_wheel_joint'
    - name:     'br_caster_wheel_joint'
    - name:     'left_suspension_joint'
    - name:     'right_suspension_joint'
    - name:     'fl_caster_suspension_joint'
    - name:     'fr_caster_suspension_joint'
    - name:     'bl_caster_suspension_joint'
    - name:     'br_caster_suspension_joint'